easy_admin:
  #    disabled_actions: ['delete']
  site_name: 'Black Friday Posadas'
  show:
    max_results: 20
  list:
    actions:
      - { name: 'show', icon: 'eye', label: '' }
      - { name: 'edit', icon: 'pencil', label: '' }
  #            - { name: 'delete', icon: 'trash', label: '' }

  design:
    brand_color: '#D41B20'
    #        form_theme: ['horizontal']
    menu:
      - { label: 'Ver web', route: 'web', icon: "eye" }
      - { label: 'Texto de la Web', entity: WebTexto, icon: "globe" }
      - { label: 'Galer√≠as', entity: WebGaleria }
      - { label: 'Rubros', entity: Rubro }
      - { label: 'Comercios', entity: Comercio }
      - { label: 'Tips para comercios', entity: TipEmpresa }
      - { label: 'Usuarios', entity: Usuario, icon: "user" }
#    assets:
#      favicon: 'bundles/app/img/favicon.png'